# Generated by Django 4.0.4 on 2022-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='person_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='telegram_alias',
            field=models.CharField(default='@Vldmr11', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
