# Generated by Django 4.0.4 on 2022-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_productname_ordermodel_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
