# Generated by Django 4.0.4 on 2022-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='location',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='product_name',
            new_name='productName',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='angel',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='shopper',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
