# Generated by Django 4.0.4 on 2022-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_location_ordermodel_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
