# Generated by Django 4.0.4 on 2022-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
