# Generated by Django 4.0.4 on 2022-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='reward',
            field=models.FloatField(),
        ),
    ]
