# Generated by Django 4.0.4 on 2022-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='size',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='weight',
            field=models.FloatField(),
        ),
    ]
