# Generated by Django 4.0.4 on 2022-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer_profile',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='deliverer_profile',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
