# Generated by Django 4.0.4 on 2022-06-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_rename_dealscompleted_profilemodel_deals_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='person_id',
        ),
    ]
